### ISSUE TITLE
Remove brackets from unlinked Roam Pages

### ISSUE THREAD

**Issue by mschrader15** [dvargas92495/generate-roam-site-action#11]
Hey y'all,

So glad I found this repo last night! (it's been an effective way to procrastinate paper writing haha)

I have a couple pages that I want to include on my generated website that have links to pages that I don't want. I would like to keep the links in roam research but have them rendered without brackets in the HTML.

Is this something you think other users will want too? Should it be the default?

As far as I see, we can just extend 

https://github.com/dvargas92495/generate-roam-site-action/blob/4ec872cf421de25cb485f7117ca2b08fd6841fa5/src/generate-site.ts#L202

To replace the remaining double brackets?

**Comment by caffo** [comment]
I agree — this should be on by default.

**Comment by dvargasfuertes** [comment]
:+1:! Feel free to submit a PR or I could get to this next week!
