### ISSUE TITLE
Support for Roam's flavor of Markdown

### ISSUE THREAD

**Issue by mschrader15** [dvargas92495/generate-roam-site-action#13]
Out of the box, https://github.com/markedjs/marked is interpreting bold and strikethrough correctly. Highlight and italics (or emphasis?) are not. 

![image](https://user-images.githubusercontent.com/57813331/103462450-dc7a6880-4cea-11eb-876e-cfd7bc3f4225.png)

![image](https://user-images.githubusercontent.com/57813331/103462367-67a72e80-4cea-11eb-9836-9bd84f21a562.png)

and the html:

```
<li>^^Highlighted^^, <strong>Bold</strong>, <del>strikethrough</del>, <strong>italics</strong></li>
```

**Comment by dvargasfuertes** [comment]
Yup, I deal with this in my Presentation extension:

https://github.com/dvargas92495/roam-js-extensions/blob/master/src/components/Presentation.tsx#L28-L47

To deal with this, I want to abstract the logic out into a common library, and then import it in both

**Comment by caffo** [comment]
Nice simple fix :)
