### ISSUE TITLE
Decouple index processing from filters

### ISSUE THREAD

**Issue by caffo** [dvargas92495/generate-roam-site-action#5]
As of right now, the index page isn't processed if not part of the filtered pages.  So if I have this config:

- Index
    - Website/Index
- Filter
    - Tagged With
        - Website/Page

I need to tag [[Website/Index]] with [[Website/Page]] for it to be processed.  It's a bit counterintuitive, no?

**Comment by dvargasfuertes** [comment]
100% agree, should just be included by default
