### ISSUE TITLE
Support "Ignoring" a block (and its children)

### ISSUE THREAD

**Issue by caffo** [dvargas92495/generate-roam-site-action#6]
Would be useful if we could ignore a block (and its subtree), essentially not rendering it's output. This allows for per-page customization in the future (like code injection to page's `head` etc).

It can also be used to tag the page with the filter tag while not rendering the link itself.

Example:

```
- [[roam/js/public-garden/ignore]]
    - Tags:: [[Website/Page]]
    - Head
        - ```javascript
alert('boom');```
```

**Comment by dvargasfuertes** [comment]
this is an incredibly cool UX. Love this idea!

**Comment by caffo** [comment]
I think this will be very important. We will be able to have things like custom titles and filenames.
